# Generated by Django 4.1.5 on 2023-02-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_esp'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='analog',
            field=models.IntegerField(default=0),
        ),
    ]
